### ISSUE TITLE
is there an active support ?

### ISSUE THREAD

**Issue by BnitoBzh** [code-corps/ember-stripe-elements#41]
I would like to make a new pull request in order to fix the component 'sendAction' depreciation, but i see that 2 valid pull requests are always pending ...

**Comment by BnitoBzh** [comment]
and next, i want to propose some new element types

**Comment by wagenet** [comment]
Unfortunately, it looks like the answer is no to the first question.

**Comment by st-h** [comment]
Would be awesome if we could get an official yes or no on this question.

**Comment by st-h** [comment]
I've temporarily re-released this add-on [here](https://www.npmjs.com/package/@st-h/ember-stripe-elements) with my PRs included. Sorry about that, but we needed an up-to-date version which does not require jquery. 
Please do let us know in case you intend to continue to maintain this add-on. Hopefully we can join forces, as I don't see any reason for having two add-ons doing the same thing and are built on the same codebase

**Comment by bartocc** [comment]
I'm going to go with your fork @st-h for the moment

**Comment by lindyhopchris** [comment]
Hi! Could we have a definitive answer to what's going on with this repo? Even if it's just to say it isn't under active support at the moment, that would at least let us know whether to use it.

There's quite an urgency to this. With the introduction of Strong Customer Authentication (SCA) in the EU on 14 September, we are having to upgrade all our Stripe flows to use their new *Payment Intent* API. On the client side, this means using the `handleCardPayment` method, as described here:
https://stripe.com/docs/payments/payment-intents/quickstart

Basically does this package support this new API, and if not: what can we do to help get it added ASAP? Or if there's no intent to update this package, we need to know that so that we can explore alternatives.

I'm happy to help out with this, but there really is an urgency with this as code has to be changed by the 14 Sept deadline otherwise payments in the EU will start to fail. It would be good to get this addon under active support as it's such a crucial addon!

cc @st-h - would be good to know your perspective, in particular if you're sticking to your fork and whether that fork does/will support `handleCardPayment`.

**Comment by st-h** [comment]
@lindyhopchris I am using my fork in production, so I am committed to maintain it unless:
- this repo will be resurrected, making my fork obsolete
- I no longer have any use case to use stripe

As long as this is the case (there currently are no plans regarding the latter one), please feel free to open up issues and/or send pull requests over at the forks repo if you encounter anything missing. We are located in the EU, so we will very likely be adopting SCA, however I have not been able to take much time to look into this or any details yet.

**Comment by lindyhopchris** [comment]
@st-h ok great, thanks for confirming! I'm starting work on the SCA changes in our app in the week commencing 8 July. So if we haven't heard back about this repo by then, I'll definitely use your fork.

**Comment by joshsmith** [comment]
Hi to everyone in this thread and a huge apology for having this slide for so long. Without going long into the details, I had a number of really big life changes recently and fell behind dramatically on my open source work.

I'm happy to try to support this again actively since I'm now able to spend more effort paying attention to GitHub notifications here.

@st-h if you'd be interested in talking more seriously about how to bring your fork in and get things up-to-date (and if interested, join as a maintainer) then I'd be happy to spend some time pairing to get things going.

Thanks for contributing your fork to the community in the meantime!

And really, sincerest apologies again to everyone impacted by my delays.

**Comment by BnitoBzh** [comment]
we definitely use @st-h fork in our production app.

**Comment by joshsmith** [comment]
@BnitoBzh to answer your original questions, feel free to introduce PRs, but probably cheaper for you to just open some new issues now laying out your proposed changes as an RFC. Thanks!

Closing this for now.

**Comment by lindyhopchris** [comment]
@joshsmith thanks for confirming, and no worries - all of us who maintain open source projects know that sometimes life has to take priority!!! if you ever need help from other contributors do let me know as we're very reliant on Stripe.

**Comment by joshsmith** [comment]
@lindyhopchris then you'd make the perfect contributor. I'd be happy to add you as a member, as well, if you're interested.

**Comment by st-h** [comment]
@joshsmith Thanks for getting back to this. Hope all is well. I would strongly prefer to incorporate my changes to this repo rather than maintaining an add-on which just duplicates what another add-on is doing. I think I already submitted all changes as PR, but I can diff again to see if I missed anything. I would also be glad to help as a maintainer.

**Comment by lindyhopchris** [comment]
yes happy to be a maintainer if that helps!

**Comment by joshsmith** [comment]
@lindyhopchris excellent, thank you! I've sent you an invite.
