### ISSUE TITLE
Switch to master as default branch?

### ISSUE THREAD

**Issue by danwenzel** [code-corps/ember-stripe-elements#51]
This repo currently uses `develop` as the default branch.  Using a branch other than `master` as the default goes against convention and can cause confusion and frustration with developers.  

Can the default be changed to `master`?

**Comment by josemarluedke** [comment]
👍 on this one.

**Comment by st-h** [comment]
Absolutely 👍 The default branch is only causing confusion and leads to work being done multiple times ( https://github.com/code-corps/ember-stripe-elements/pull/56 , https://github.com/code-corps/ember-stripe-elements/pull/42 )

**Comment by lindyhopchris** [comment]
So where I work we always use `develop` as the default branch, so that PRs are automatically created against `develop` instead of `master`.

This is because we use `git flow` - i.e. `develop` is the next release, `master` is the current production release.

I think something along those lines is why the `develop` branch is the default here - i.e. to keep PRs against `develop` not `master`. The cause of the confusion IMHO is that there hasn't been a tagged release for a while so `master` and `develop` have got out of sync (though all recent merges have been on `develop`).

Personally I'd prefer to keep `develop` as the default branch but sort out #63 i.e. get a tagged version out.

**Comment by st-h** [comment]
@lindyhopchris I also know that concept from previous companies I worked at. Usually this has been used as a means to QA a particular combination of PRs on a dedicated test system. However, I think it is kind of uncommon among the ember ecosystem to use a different default branch, and I personally have never found a need to do so. If we want to keep the dev branch, we should make it very clear within the README that this repo follows its own conventions and show people where they should look for already implemented fixes to avoid work being done multiple times.

**Comment by lindyhopchris** [comment]
Ok makes sense. I'd prefer to keep both branches though - so that you can bugfix the current version (on `master`) while deving the next version (on `develop`).

**Comment by danwenzel** [comment]
Closing this, as it does not apply to the new `adopted-ember-addons` version of this library
